### ISSUE TITLE
[Suggestion]: Optimize water calculations

### ISSUE THREAD

**Issue by pworty** [Fuzss/permanentsponges#4]
### Suggestion (Required)

LiquidAbsorptionHelper as I suppose checks for wheter water should be kept out by sponges even if they are not present, causing higher server lag when near any water sources

**Comment by Fuzss** [comment]
The code in `LiquidAbsorptionHelper` only runs when a fluid state update is caused which is quite efficient. It does not have any effect when moving around static fluids. The sponges being implemented as POIs is also quite efficient, since the whole lookup is well optimized on vanilla's end.

If you have any concrete improvements feel free to open a PR!
