### ISSUE TITLE
[Crash]: Possible Conflict with Lithium (somehow)

### ISSUE THREAD

**Issue by Gamemassa** [Fuzss/permanentsponges#5]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

21.0.0

### Other Mods Involved (Required)

Yes

### Notes (Required)

Permanent Sponges was just updated for 1.21 this morning, so I tried loading into my SP world after adding it to my modpack, and I got a crash report that I'm pretty sure is saying it's conflicting with Lithium.

### Crash Report (Required)

https://mclo.gs/ECZZ0NK

### latest.log (Optional)

https://mclo.gs/HbYdUCr

**Comment by Fuzss** [comment]
This is an issue caused by Lithium. They pass a `null` block position value to a method that expects a non-null value. Please report the issue to them.

https://github.com/CaffeineMC/lithium-fabric/blob/427dd75ffc922cc1858c1db4b283cc54744567e0/src/main/java/me/jellysquid/mods/lithium/mixin/block/fluid/flow/FlowableFluidMixin.java#L293

**Comment by Gamemassa** [comment]
Ok, thanks for confirming. I'll pass this along.

**Comment by Gamemassa** [comment]
Hey Fuzs, I noticed you added a workaround for this issue. Did the Lithium team tell you they couldn't fix it on their end? I haven't heard from them.

**Comment by Fuzss** [comment]
I added a simple workaround, but this is still an issue caused by Lithium other mods might run into as well.
